In [2]:
# Con def podemos definir una función a nuestra elección
def suma(a, b):
    return a + b
print(suma(3, 5))  # Llamamos a la función con dos números


8


In [4]:
def calculadora(a, b, operacion):
    if operacion == "+":
        return a + b
    elif operacion == "-":
        return a - b
    elif operacion == "*":
        return a * b
    elif operacion == "/":
        return a / b
    elif operacion == "%":
        return a % b
    else:
        return "Operación no válida"

a = int(input("Ingrese número a: "))
b = int(input("Ingrese número b: "))
op = input("Ingrese el tipo de operación aritmética (+, -, *, /, %): ")

resultado = calculadora(a, b, op)
print(f"Número a: {a}")
print(f"Número b: {b}")
print("Resultado:", resultado)


Número a: 3
Número b: 9
Resultado: -6


In [ ]:
import numpy as np

def crear_matriz(n):
    matriz = np.zeros((n, n), dtype=int)
    
    for i in range(n):
        for j in range(n):
            valor = int(input(f"Dime el dato en la fila {i+1} y la columna {j+1}: "))
            matriz[i][j] = valor 
    return matriz

n = int(input("Escriba el parámetro n para definir el tamaño de la matriz cuadrada: "))
matriz = crear_matriz(n)

print("Su matriz es:")
print(matriz)

transpuesta = matriz.T
print("La transpuesta de la matriz es:")
print(transpuesta)


Su matriz es:
[[1 2]
 [3 4]]
La transpuesta de la matriz es:
[[1 3]
 [2 4]]


In [8]:
def estacion(mes, dia):
    dias_mes = {
        "enero": 31, "febrero": 28, "marzo": 31,
        "abril": 30, "mayo": 31, "junio": 30,
        "julio": 31, "agosto": 31, "septiembre": 30,
        "octubre": 31, "noviembre": 30, "diciembre": 31
    }

    if mes not in dias_mes:
        return "Mes inválido"

    if dia < 1 or dia > dias_mes[mes]:
        return f"Error: {mes} no tiene {dia} días"

    if (mes == "diciembre" and dia >= 21) or mes in ["enero", "febrero"] or (mes == "marzo" and dia < 21):
        return "invierno"
    elif (mes == "marzo" and dia >= 21) or mes in ["abril", "mayo"] or (mes == "junio" and dia < 21):
        return "primavera"
    elif (mes == "junio" and dia >= 21) or mes in ["julio", "agosto"] or (mes == "septiembre" and dia < 21):
        return "verano"
    else:
        return "otoño"


mes = input("Ingrese el nombre del mes: ").lower()
dia = int(input("Ingrese el día que desea consultar: "))

resultado = estacion(mes, dia)
print(f"Para el día {dia} del mes {mes} estaríamos en {resultado}")


Para el día 12 del mes junio estaríamos en primavera


In [1]:
import numpy as np

try:
    filas = int(input("Ingrese el número de filas: "))
    columnas = int(input("Ingrese el número de columnas: "))

    matriz_usuario = []
    print("\nIngrese los elementos de la matriz:")
    for i in range(filas):
        fila = []
        for j in range(columnas):
            valor = int(input(f"Ingrese el valor para la posición [{i}][{j}]: "))
            fila.append(valor)
        matriz_usuario.append(fila)

    matriz_usuario = np.array(matriz_usuario)

    matriz_aleatoria = np.random.randint(0, 10, (filas, columnas))

    matriz_suma = matriz_usuario + matriz_aleatoria

    print("Matriz ingresada por el usuario:\n", matriz_usuario)
    print("\nMatriz aleatoria:\n", matriz_aleatoria)
    print("\nSuma de ambas matrices:\n", matriz_suma)

except ValueError:
    print("Error: Debe ingresar solo números enteros.")



Ingrese los elementos de la matriz:
Matriz ingresada por el usuario:
 [[1 2]
 [3 4]]

Matriz aleatoria:
 [[3 9]
 [5 8]]

Suma de ambas matrices:
 [[ 4 11]
 [ 8 12]]


In [10]:
reseñas = []
for i in range(3):
    reseña = input(f"Ingrese la reseña {i+1}: ")
    reseñas.append(reseña)

reseñas_limpias = []
for r in reseñas:
    r = r.lower() 
    for signo in ".,!?":
        r = r.replace(signo, "")
    reseñas_limpias.append(r)

frecuencias = {}
for r in reseñas_limpias:
    palabras = r.split()  
    for palabra in palabras:
        frecuencias[palabra] = frecuencias.get(palabra, 0) + 1

top3 = sorted(frecuencias.items(), key=lambda x: x[1], reverse=True)[:3]

print("\nLas 3 palabras más frecuentes son:")
for palabra, cantidad in top3:
    print(f"{palabra}: {cantidad} veces")



Las 3 palabras más frecuentes son:
a: 3 veces
